# -----------------------------------------------------------------------------
# General Site Settings
# -----------------------------------------------------------------------------

title: "Seyed Ahmad Mousavi's Portfolio"  # Set your website's title
first_name: "Seyed Ahmad"
middle_name: "Mousavi"
email: "Ahmad1414141412@gmail.com"
description: >
  A simple portfolio website for academics using Jekyll and the al-folio theme.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.
  Photos from <a href="https://unsplash.com" target="_blank">Unsplash</a>.
keywords: jekyll, portfolio, academics, personal website, academic website
lang: en  # Set your website's language (en = English)
icon: 💻  # Favicon icon
url: https://AhmadMousavi1214.github.io  # Website URL
baseurl: ""  # Leave blank for root, otherwise specify the subpath
last_updated: false  # Set to true if you want the last updated date to appear in footer

# -----------------------------------------------------------------------------
# Theme and Customization
# -----------------------------------------------------------------------------

repo_theme_light: default  # Light mode theme for GitHub stats
repo_theme_dark: dark  # Dark mode theme for GitHub stats
repo_trophies:
  enabled: true
  theme_light: flat  # Light theme for GitHub trophies
  theme_dark: gitdimmed  # Dark theme for GitHub trophies

# -----------------------------------------------------------------------------
# RSS Feed and Social Links
# -----------------------------------------------------------------------------

rss_icon: true  # Enable RSS feed

# Social Media Integration
github_username: AhmadMousavi1214  # GitHub username
telegram_username: AhmadMousavi141412  # Telegram username
linkedin_username: # Add your LinkedIn username
whatsapp_number: # Add your WhatsApp number in international format
instagram_id: # Add your Instagram username
youtube_id: # Add your YouTube channel ID
twitter_username: # Add your Twitter handle

# -----------------------------------------------------------------------------
# Layout and Display Settings
# -----------------------------------------------------------------------------

navbar_fixed: true  # Fix navbar at the top
footer_fixed: true  # Fix footer at the bottom
max_width: 800px  # Maximum width for the site content

# -----------------------------------------------------------------------------
# Open Graph & SEO
# -----------------------------------------------------------------------------

serve_og_meta: false  # Enable Open Graph meta tags for social media
serve_schema_org: false  # Enable Schema.org markup for search engines

# -----------------------------------------------------------------------------
# Blog Settings
# -----------------------------------------------------------------------------

blog_name: al-folio
blog_description: A simple whitespace theme for academics
pagination:
  enabled: true  # Enable pagination for blog
  limit: 5  # Number of posts per page
related_blog_posts:
  enabled: true  # Enable related blog posts
  max_related: 5  # Maximum related posts

# Giscus comments integration (if using)
giscus:
  repo: "<your-github-user>/<your-repo-name>"
  repo_id: # Specify repo ID for Giscus
  category: Comments
  strict: 1  # Enable strict mode
  reactions_enabled: 1  # Enable emoji reactions
  input_position: bottom
  theme: preferred_color_scheme

# -----------------------------------------------------------------------------
# Analytics and Verification
# -----------------------------------------------------------------------------

google_analytics: # Add your Google Analytics ID (e.g., UA-XXXXX-X)
google_site_verification: # Add your Google verification ID
bing_site_verification: # Add your Bing verification ID

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

# -----------------------------------------------------------------------------
# Jekyll Settings and Plugins
# -----------------------------------------------------------------------------

markdown: kramdown  # Markdown processor
highlighter: rouge  # Syntax highlighter for code
plugins:
  - jekyll-archives
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-toc

# -----------------------------------------------------------------------------
# Image Optimization and WebP
# -----------------------------------------------------------------------------

imagemagick:
  enabled: true  # Enable image optimization
  widths:
    - 480
    - 800
    - 1400
  input_formats:
    - .jpg
    - .png
    - .gif
  output_formats:
    webp: "-quality 85"

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics: false  # Set to true if you want to use Google Analytics
